### ISSUE TITLE
Dancer-Plugin-DBIC-0.1506 breaks AtomBus-1.0404

### ISSUE THREAD

**Issue by andk** [ironcamel/AtomBus#4]
As per subject. I just tuned a few of my smokers up and down between D:P:DBIC 0.1505 and 0.1506 and found that upgrading makes AtomBus fail and downgrading makes it pass.

Let me know if you need more infos,

HTH&&Regards

**Comment by ironcamel** [comment]
Thanks for letting me know. I found the problem. I need to update the AtomBus tests. It should be an easy fix and I'll do it soon. So are you using AtomBus? If so, what are you using it for? Thanks.

**Comment by andk** [comment]
> > > > > On Sun, 15 Apr 2012 06:38:07 -0700, Naveed Massjouni reply@reply.github.com said:
> 
> Thanks for letting me know. I found the problem. I need to update
> the AtomBus tests. It should be an easy fix and I'll do it soon. So
> are you using AtomBus? If so, what are you using it for? Thanks.

No, I'm not using AtomBus, I'm only a notorious
cpan-reporters-fail-reports-watcher:)

## 

andreas

**Comment by ironcamel** [comment]
Fixed in 1.0405
