### ISSUE TITLE
please tag release

### ISSUE THREAD

**Issue by jonassmedegaard** [ironcamel/AtomBus#5]
Some CPAN releases, including latest 1.0405, is not represented with a git tag.

Please consider tag all releases, as (if nothing else) that helps redistributors more confidently tie CPAN tarballs to the more fine-grained development sources in git.

**Comment by ironcamel** [comment]
Sure thing. I have pushed the 1.0405 tag https://github.com/ironcamel/AtomBus/tree/v1.0405

**Comment by jonassmedegaard** [comment]
excellent - that was quick!! :-)
